### ISSUE TITLE
wait_to_appear with id containing a space

### ISSUE THREAD

**Issue by geokala** [hitchtest/hitchselenium#5]
When an ID contains a space it appears that there is no way to wait for it to appear using wait_to_appear.

It would be good if there was a way to wait_to_appear for IDs with spaces in.

**Comment by crdoconnor** [comment]
According to the HTML4/5 specs, spaces aren't considered valid in HTML IDs:

https://stackoverflow.com/questions/70579/what-are-valid-values-for-the-id-attribute-in-html

Were you trying to put spaces in your IDs in order to make your tests look cleaner/more readable?

**Comment by geokala** [comment]
Ah, interesting. I didn't realise that, and firefox didn't complain. I'll have to have a dig.

I'm creating some tests to confirm expected behaviour with various input (e.g. various special characters, etc).

Given that it's going against spec, I'll have to dig and see what's happening under the hood. I suspect it's a case of the browser being more permissive than it should be.

Either way, not an issue with your plugin!
